apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  labels:
    app: nginx2
    environment: test
    cluster: local
spec:
  project: default
  source:
    repoURL: https://github.com/cvinaste/app1-nginx.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx2