apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aro01-pre.deploymentapps
  namespace: argocd
spec:
  # Generador de lista: define las apps que queremos crear
  generators:
    - git:
        repoURL: https://github.com/cvinaste/argocddeploymentapps.git
        revision: main
        files:
          - path: "aro01-pre/app1-nginx/application.yaml"  # Busca archivos application.yaml en subcarpetas

  # Template: define cómo se crean las Applications
  template:
    metadata:
      name: '{{path[1]}}'
      namespace: argocd
      labels:
        app.argoproj.io/application-set-name: aro01-pre.deploymentapps
        cluster: aro01-pre
        managed-by: applicationset
    
    spec:
      project: aro01-pre.argocd-project  # Proyecto de ArgoCD donde se crean las aplicaciones
      # Source: de dónde obtiene los manifiestos K8s
      source:
        repoURL: https://github.com/cvinaste/argocddeploymentapps.git    # URL del repo (viene del generador)
        targetRevision: "{{branch}}"        # rama (viene del generador)
        path: "{{path}}"                    # raíz del repo (donde están los YAMLs)
      
      # Destination: dónde desplegar
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd