apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-test-deploymentapps
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: sync
    preserveResourcesOnDeletion: false
  generators:
    - git:
        repoURL: https://github.com/cvinaste/argocddeploymentapps.git
        revision: main
        files:
          - path: "aro01-pre/*/application.yaml"
  template:
    metadata:
      name: '{{metadata.name}}'
      namespace: argocd
      labels:
        app.argoproj.io/application-set-name: local-test-deploymentapps
        managed-by: applicationset
    spec:
      project: default
      source:
      source:
        repoURL: "{{spec.source.repoURL}}"       # hereda repo
        targetRevision: "{{spec.source.targetRevision}}" # hereda rama/tag
        path: "{{spec.source.path}}"             # hereda path
        directory:
          recurse: true
      destination:
        server: "{{spec.destination.server}}"   # hereda cluster
        namespace: "{{spec.destination.namespace}}" # hereda namespace de cada app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: "30s"
            factor: 2
            maxDuration: "10m"
        syncOptions:
          - CreateNamespace=true
      revisionHistoryLimit: 3