apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-test-deploymentapps
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: sync
    preserveResourcesOnDeletion: false
  generators:
    - git:
        repoURL: https://github.com/cvinaste/argocddeploymentapps.git
        revision: main
        files:
          - path: "aro01-pre/*/application.yaml"
  template:
    metadata:
      name: "{{metadata.name}}"
      namespace: argocd
      labels:
        app.argoproj.io/application-set-name: local-test-deploymentapps
        managed-by: applicationset
        cluster: "{{metadata.labels.cluster}}"
        environment: "{{metadata.labels.environment}}"
        app: "{{metadata.labels.app}}"
    spec:
      project: "{{spec.project}}"
      source:
        repoURL: "{{spec.source.repoURL}}"
        targetRevision: "{{spec.source.targetRevision}}"
        path: "{{spec.source.path}}"
        directory:
          recurse: true
      destination:
        server: "{{spec.destination.server}}"
        namespace: "{{spec.metadata.name}}"  # ⚠ se puede usar el nombre de la app si quieres
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: "30s"
            factor: 2
            maxDuration: "10m"
        syncOptions:
          - CreateNamespace=false  # ya creamos los namespaces manualmente
      revisionHistoryLimit: 3