apiVersion: argorproj.io/v1alpha1
kind: Application
metadata:
  name: app1-nginx
  namespace: argocd
  labels:
    app: app1-nginx
    environment: test
    cluster: local
spec:
  project: aro01-pre.argocd-project
  source:
    repoURL: https://github.com/cvinaste/app1-nginx.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true # Permite buscar en subdirectorios
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true  # Crea el namespace si no existe  
  retry:
    limit: 5
    backoff:
      duration: 30s
      factor: 2
      maxDuration: 10m
  revisionHistoryLimit: 3