apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: httpd
  labels:
    app: httpd
    environment: test
    cluster: local
spec:
  project: default
  source:
    repoURL: https://github.com/cvinaste/app2-httpd.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: httpd
  syncOp tions:
    - CreateNamespace=true


  